Title: Chola Lisa T N Mc Auley 
logo: Background off.png
description: I am an experienced data analyst who has several years of experience in Microsoft Excel, SQL, and Power BI. I have worked with diverse data sources where I cleaned and transformed complex datasets into actionable insights, helping businesses to make informed decisions.
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
